# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumbTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=15)),
                ('number_field1', models.IntegerField()),
                ('number_field2', models.IntegerField()),
                ('number_field3', models.IntegerField()),
            ],
        ),
    ]
